# Generated by Django 3.2.5 on 2021-07-13 16:10

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleYearMake', models.PositiveSmallIntegerField(default=2021)),
                ('vehicleModel', models.CharField(max_length=80)),
                ('vehicleNumber', models.CharField(max_length=30)),
                ('vehiclePrice', models.DecimalField(decimal_places=2, default=100000, max_digits=10, validators=[django.core.validators.MinValueValidator(30000)])),
                ('quotationPrice', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('covWind', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Windscreen coverage')),
                ('covPass', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Passenger liability coverage')),
                ('covFlood', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Flood, Windstorm,Landslide or Subsidence coverage')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='api.customer')),
            ],
        ),
    ]
